{"name": "test_contactus_form_send", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\tOrdinal0 [0x003D6903+2517251]\n\tOrdinal0 [0x0036F8E1+2095329]\n\tOrdinal0 [0x00272848+1058888]\n\tOrdinal0 [0x0029D448+1233992]\n\tOrdinal0 [0x0029D63B+1234491]\n\tOrdinal0 [0x002C7812+1406994]\n\tOrdinal0 [0x002B650A+1336586]\n\tOrdinal0 [0x002C5BBF+1399743]\n\tOrdinal0 [0x002B639B+1336219]\n\tOrdinal0 [0x002927A7+1189799]\n\tOrdinal0 [0x00293609+1193481]\n\tGetHandleVerifier [0x00565904+1577972]\n\tGetHandleVerifier [0x00610B97+2279047]\n\tGetHandleVerifier [0x00466D09+534521]\n\tGetHandleVerifier [0x00465DB9+530601]\n\tOrdinal0 [0x00374FF9+2117625]\n\tOrdinal0 [0x003798A8+2136232]\n\tOrdinal0 [0x003799E2+2136546]\n\tOrdinal0 [0x00383541+2176321]\n\tBaseThreadInitThunk [0x7600343D+18]\n\tRtlInitializeExceptionChain [0x772E9812+99]\n\tRtlInitializeExceptionChain [0x772E97E5+54]", "trace": "self = <tests.test_contactus_page.TestContactUsPage object at 0x0349C550>\n\n    @allure.story(\"Проверка корректной отправки формы обратной связи\")\n    def test_contactus_form_send(self):\n        \"\"\"Verifying that contact us form sends successfully\"\"\"\n        contact_us = ContactUsPage(self.driver)\n>       contact_us.attach_txt_file(str(Path(pathlib.Path.cwd() / 'ContactUs form.txt')))\n\ntests\\test_contactus_page.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\contactus_page.py:15: in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\nbase\\seleniumbase.py:29: in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"2c9c55f2efc02558122296d21fe02a67\")>, method = <function presence_of_element_located.<locals>._predicate at 0x0349EDF0>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       Backtrace:\nE       \tOrdinal0 [0x003D6903+2517251]\nE       \tOrdinal0 [0x0036F8E1+2095329]\nE       \tOrdinal0 [0x00272848+1058888]\nE       \tOrdinal0 [0x0029D448+1233992]\nE       \tOrdinal0 [0x0029D63B+1234491]\nE       \tOrdinal0 [0x002C7812+1406994]\nE       \tOrdinal0 [0x002B650A+1336586]\nE       \tOrdinal0 [0x002C5BBF+1399743]\nE       \tOrdinal0 [0x002B639B+1336219]\nE       \tOrdinal0 [0x002927A7+1189799]\nE       \tOrdinal0 [0x00293609+1193481]\nE       \tGetHandleVerifier [0x00565904+1577972]\nE       \tGetHandleVerifier [0x00610B97+2279047]\nE       \tGetHandleVerifier [0x00466D09+534521]\nE       \tGetHandleVerifier [0x00465DB9+530601]\nE       \tOrdinal0 [0x00374FF9+2117625]\nE       \tOrdinal0 [0x003798A8+2136232]\nE       \tOrdinal0 [0x003799E2+2136546]\nE       \tOrdinal0 [0x00383541+2176321]\nE       \tBaseThreadInitThunk [0x7600343D+18]\nE       \tRtlInitializeExceptionChain [0x772E9812+99]\nE       \tRtlInitializeExceptionChain [0x772E97E5+54]\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "description": "Verifying that contact us form sends successfully", "steps": [{"name": "Прикрепление файла", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\tOrdinal0 [0x003D6903+2517251]\n\tOrdinal0 [0x0036F8E1+2095329]\n\tOrdinal0 [0x00272848+1058888]\n\tOrdinal0 [0x0029D448+1233992]\n\tOrdinal0 [0x0029D63B+1234491]\n\tOrdinal0 [0x002C7812+1406994]\n\tOrdinal0 [0x002B650A+1336586]\n\tOrdinal0 [0x002C5BBF+1399743]\n\tOrdinal0 [0x002B639B+1336219]\n\tOrdinal0 [0x002927A7+1189799]\n\tOrdinal0 [0x00293609+1193481]\n\tGetHandleVerifier [0x00565904+1577972]\n\tGetHandleVerifier [0x00610B97+2279047]\n\tGetHandleVerifier [0x00466D09+534521]\n\tGetHandleVerifier [0x00465DB9+530601]\n\tOrdinal0 [0x00374FF9+2117625]\n\tOrdinal0 [0x003798A8+2136232]\n\tOrdinal0 [0x003799E2+2136546]\n\tOrdinal0 [0x00383541+2176321]\n\tBaseThreadInitThunk [0x7600343D+18]\n\tRtlInitializeExceptionChain [0x772E9812+99]\n\tRtlInitializeExceptionChain [0x772E97E5+54]\n\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\pages\\contactus_page.py\", line 15, in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\base\\seleniumbase.py\", line 29, in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 89, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "file_path", "value": "'C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\ContactUs form.txt'"}], "start": 1642844162188, "stop": 1642844172190}], "attachments": [{"name": "Screenshot", "source": "7429dd4d-b94d-4a10-97ca-2cb48dfc42f7-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "a5fdf560-2f9a-4621-a395-bd3a4b2a0326-attachment.txt", "type": "text/plain"}], "start": 1642844160743, "stop": 1642844172221, "uuid": "ccfc1670-c0df-42cc-aed2-c89b938860a8", "historyId": "eec3f3bdb32471cd8a64ec4144811604", "testCaseId": "5eee35e243bc5160f7cb10f7b5804ad4", "fullName": "tests.test_contactus_page.TestContactUsPage#test_contactus_form_send", "labels": [{"name": "feature", "value": "Тест формы обратной связи"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Проверка корректной отправки формы обратной связи"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_driver_init')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contactus_page"}, {"name": "subSuite", "value": "TestContactUsPage"}, {"name": "host", "value": "ArtemKozlov"}, {"name": "thread", "value": "1344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contactus_page"}]}