{"name": "test_contactus_form_error", "status": "broken", "statusDetails": {"message": "AttributeError: 'ContactUsPage' object has no attribute 'is_present'", "trace": "self = <tests.test_contactus_page.TestContactUsPage object at 0x03AADE38>\n\n    @allure.story(\"Проверка появления ошибки при отправки формы обратной связи с незаполненным полем 'Message'\")\n    def test_contactus_form_error(self):\n        \"\"\"Verifying that error message appears if Message area is empty\"\"\"\n        contact_us = ContactUsPage(self.driver)\n        contact_us.attach_txt_file(str(Path(pathlib.Path.cwd() / 'ContactUs form.txt')))\n>       contact_us.select_sh_dropdown_list_by_text(\"Customer service\")\n\ntests\\test_contactus_page.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\contactus_page.py:23: in select_sh_dropdown_list_by_text\n    select = self._get_select_list('xpath', ContactUsPageLocators.subject_heading_select)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.contactus_page.ContactUsPage object at 0x03C89370>\nfind_by = 'xpath', locator = \"//select[@id='id_contact']\"\n\n    def _get_select_list(self, find_by: str, locator: str):\n>       return Select(self.is_present(find_by, locator))\nE       AttributeError: 'ContactUsPage' object has no attribute 'is_present'\n\nbase\\seleniumbase.py:60: AttributeError"}, "description": "Verifying that error message appears if Message area is empty", "steps": [{"name": "Прикрепление файла", "status": "passed", "parameters": [{"name": "file_path", "value": "'C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\ContactUs form.txt'"}], "start": 1642581712470, "stop": 1642581712544}, {"name": "Выбор \"Subject Heading\"", "status": "broken", "statusDetails": {"message": "AttributeError: 'ContactUsPage' object has no attribute 'is_present'\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\pages\\contactus_page.py\", line 23, in select_sh_dropdown_list_by_text\n    select = self._get_select_list('xpath', ContactUsPageLocators.subject_heading_select)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\base\\seleniumbase.py\", line 60, in _get_select_list\n    return Select(self.is_present(find_by, locator))\n"}, "parameters": [{"name": "text", "value": "'Customer service'"}], "start": 1642581712544, "stop": 1642581712544}], "attachments": [{"name": "Screenshot", "source": "5727141c-41ff-49b3-98c2-9a86819b7e3e-attachment.png", "type": "image/png"}], "start": 1642581707983, "stop": 1642581712545, "uuid": "d6524c6d-d89b-45b5-956c-bb937e8970b0", "historyId": "3afa3963dd0ea7e6116d37ac1b81cb63", "testCaseId": "0419b764a652c09b017d94f58deb9b97", "fullName": "tests.test_contactus_page.TestContactUsPage#test_contactus_form_error", "labels": [{"name": "story", "value": "Проверка появления ошибки при отправки формы обратной связи с незаполненным полем 'Message'"}, {"name": "feature", "value": "Тест формы обратной связи"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_driver_init')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contactus_page"}, {"name": "subSuite", "value": "TestContactUsPage"}, {"name": "host", "value": "ArtemKozlov"}, {"name": "thread", "value": "4940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contactus_page"}]}